name: build all packages 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch and if tags are created 
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]



  workflow_dispatch:
  
jobs:
  packages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker 

      - name: build 
        run: python3 ./container-build.py
      